# Task 1
####  Open it and inspect its structure. Find out which columns contain he district name (Fylkenavn) party code (Partikode)number of votes received (Antall stemmer totalt)

#### Write a program that
- reads the file and counts the total number of votes for each party across all districts
- prints the results in a table, starting with the party with the largest number of votes
- Modify your program so that it also prints the percentage of votes received by each party (2 decimals).
- Further extend your program so that it marks the parties that received at least 4% of the vote.
- Turn your code into a function that takes the file name and the number of parties to include in the table as arguments. Hint: to indent several lines simultaneously, mark them and hit "Tab". Use the function to print the table once with 3 and once with 7 parties.
- Modify the code so that giving the number of parties to tabulate becomes optional. If the user calls the function with just the filename, all parties should be included in the table.

In [139]:
import pandas as pd

def parti(file_path, number_of_parties=None):

    df = pd.read_csv(file_path, sep=';')

    df = df.groupby(['Partinavn'], as_index=False).sum().sort_values(['Antall stemmer totalt'], ascending=False)

    df = df[['Partinavn', 'Antall stemmer totalt']]

    total_votes = df['Antall stemmer totalt'].sum()
    

    df['Precentage'] = df['Antall stemmer totalt'] / total_votes

    df.round(2)

    df['Marked'] = ''

    df.loc[df['Precentage'] < 0.04, 'Marked'] = '*'

    if number_of_parties == None:
        return df
    else:
        return df.head(number_of_parties)

file = "data\\2021-09-14_party distribution_1_st_2021.csv"

parti(file,3)

          Partinavn  Antall stemmer totalt  Precentage Marked
1   Arbeiderpartiet                 761152    0.261882
9             Høyre                 590736    0.203249
24    Senterpartiet                 392193    0.134938

In [57]:
parti(file, 7)

                         Partinavn  Antall stemmer totalt  Precentage Marked
1                  Arbeiderpartiet                 761152    0.261882
9                            Høyre                 590736    0.203249
24                   Senterpartiet                 392193    0.134938
6               Fremskrittspartiet                 338129    0.116337
23  SV - Sosialistisk Venstreparti                 216082    0.074345
22                            Rødt                 135613    0.046659
25                         Venstre                 129453    0.044540

# Task 2

#### Assume that we have sentences of the form

- Ali and Per and friends.
- Kari and Joe know each other.
- James has known Peter since school days.

#### The common structure here is that each sentence contains two names and that the names are the only words beginning with capital letters. Create a regular expression that:

- matches these sentences (one sentence at a time)
- collects the names in groups

#### and write a program that can go through a list of such sentences and print a table such as:

      Friendships      
-----------------------
       Ali - Per       
      Kari - Joe       
     James - Peter     

#### Assume that

- each sentence begins with a name
- all names only contain letters from A–Z and a–z
- that all names have at least two letters.
- Make sure the program is efficient and works for all sentences with two names which fulfill the previously mentioned rules.

In [136]:
import re

txt = "Hakon og Lars er venner"
txt2 = "Per og Morten er kompiser"
txts = [txt,txt2]

personner = re.findall('[A-Z][a-z]+', txt2)

def find_friends(input_strs):
    n = len(input_strs)
    print(f'{"Friendships":>17}')
    print(f'{"-------------------":>21}')

    for i in range(n):
        setning = input_strs[i]
        venner = re.findall('[A-Z][a-z]+', setning)

        print(f'{venner[0]:>10} - {venner[1]:<10}')

find_friends(txts)

      Friendships
  -------------------
     Hakon - Lars
       Per - Morten